---
- name: Run Job Template on AAP
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run job template for starting VM
      ansible.builtin.uri:
        url: "https://{{ lookup('ansible.builtin.env', 'AAP_HOST') }}/api/v2/job_templates/{{ lookup('ansible.builtin.env', 'JOB_TEMPLATE_ID') }}/launch/"
        validate_certs: false
        method: POST
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ lookup('ansible.builtin.env', 'AAP_SECRET') | ansible.builtin.regex_replace('\n+', '') }}"
        body:
          extra_vars:
            vm_name: "{{ event.payload.vm_name }}"
        body_format: json
        status_code: 201
